### ISSUE TITLE
Reviewer2 unable to find files inside of a folder

### ISSUE THREAD

**Issue by Dylan-e** [broadinstitute/reviewer2#2]
When trying to use reviewer2, the command
py -m reviewer2 
to run it while inside a folder containing the files, it gets an error, saying it can't find any images or datafiles. 

![errror](https://user-images.githubusercontent.com/71038473/119570034-68596380-bd64-11eb-8de2-2e24ed61d94a.JPG)

I am on Windows.

**Comment by bw2** [comment]
Hi @Dylan-e , thanks for reporting this issue. 
Please update to v0.9.20 and try again. 
Also, the web interface doesn't work in Internet Explorer. Please use Firefox or Chrome.

**Comment by Dylan-e** [comment]
Thank  you, I am now able to start the server.
