### ISSUE TITLE
Opening very large numbers of images crashes the tab

### ISSUE THREAD

**Issue by sclamons** [broadinstitute/reviewer2#3]
If flipbook is asked to open a very large number of images on a single page (somewhere between 500 and 1,000 on my laptop), the web page it creates will eat up all available memory until it crashes.

**Comment by bw2** [comment]
Thanks for reporting the issue. I should split the main table into pages (with around 200 rows per page by default).

**Comment by sclamons** [comment]
200 might still be too many -- I just tried with 250 images, and it still crashes after eating ~6-7 GB of RAM. The SVGs themselves are only ~150 Mb total, but when opened in an editor (Affinity Designer) they take up ~100 Mb each, so I guess there's a ~200-fold difference between SVG and raw image?

**Comment by sclamons** [comment]
Related, though I'm not sure flipbook has any control over this: Chrome (96.0.4664.93) won't give back memory used by a flipbook-browsing tab, so if you flip through a bunch of images it eventually hits a memory error and the tab crashes. Safari (15.1) doesn't seem to do this -- it gives back its memory after a bit.

**Comment by bw2** [comment]
I might be misunderstanding the issue. I initially thought the home page (which has the [table](https://broadinstitute.github.io/StrPileups/) listing all images) was crashing, but now that I read this again, it sounds like you've grouped your images so that one of the image pages has 100's of images on it instead of 1 image (like [here](https://broadinstitute.github.io/StrPileups/page_GE_case25.html)). Is that correct?

**Comment by sclamons** [comment]
Yes to the second example. I have a bunch of folders, each of which has 100s of images in them.

**Comment by bw2** [comment]
This might be a browser limitation that FlipBook can't avoid. Currently, FlipBook loads the .svg images using a simple html img tag. To support 100s of images, it would need to switch to some sort of delayed-loading mechanism where the image is only loaded after the user scrolls to (or near) it. 

Multiple images per page were initially intended for comparing calls from individuals in a single family or from several replicates. What is the use case for loading 100+ images on a single page?
